plugin_blacklist:
# common
- ftp
- safety_area
- hil
# extras
- altitude
- debug_value
- image_pub
- px4flow
#- vibration
#- vision_speed_estimate
- wheel_odometry

plugin_whitelist:
- 'sys_*'
- actuator_control
- vision_speed_estimate
- vision_pose_estimate
